name: process-ipcc
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - dask
  - zarr
  - netcdf4
  - pandas
  - matplotlib
  - cartopy
  - tqdm
  - pip
  - cdsapi
  - pynio
  - gitpython
